services:
  - type: web
    name: movie-review-app
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y chromium chromium-driver
      pip install -r requirements.txt
    startCommand: gunicorn app:app